# Generated by Django 4.2.16 on 2025-03-08 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='point_conversion_rate',
        ),
    ]
